# Generated by Django 5.1.6 on 2025-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuscaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('resultados', models.JSONField()),
            ],
        ),
    ]
